CREATE TABLE IF NOT EXISTS users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    login       VARCHAR(255) NOT NULL,
    name        VARCHAR(255),
    birthday    DATE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_login UNIQUE (login)
    );

CREATE TABLE IF NOT EXISTS mpa_ratings (
    id      INTEGER PRIMARY KEY,
    name    VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS genres (
    id      INTEGER PRIMARY KEY,
    name    VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     VARCHAR(200) NOT NULL,
    release_date    DATE NOT NULL,
    duration        INTEGER NOT NULL,
    mpa_id          INTEGER NOT NULL,
    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_id) REFERENCES mpa_ratings(id)
    );

CREATE TABLE IF NOT EXISTS film_genres (
    film_id     INTEGER NOT NULL,
    genre_id    INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genres_film FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_film_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(id)
    );

CREATE TABLE IF NOT EXISTS film_likes (
    film_id     INTEGER NOT NULL,
    user_id     INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_film_likes_film FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_film_likes_user FOREIGN KEY (user_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS friendships (
    user_id     INTEGER NOT NULL,
    friend_id   INTEGER NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendship_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_friendship_friend FOREIGN KEY (friend_id) REFERENCES users(id)
    );